import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
 
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Survive The Void</title>
        <meta name="description" content="Generated by a couple of legends by the name of Alex and JP" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Survive The Void
        </h1>

        <p className={styles.description}>
          The world's <i>greatest</i> drinking game
        </p>

        <div className={styles.card}>
          <Link href="/test">
            <div className={styles.cardContent}>
              <h2>Let's get started!</h2>
              <p>Click here to select the number of players</p>
            </div>
          </Link>
        </div>
      
      </main>
      
    </div>
  )
}
